name: Django Project Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check Docker and Docker Compose version
      run: |
            docker --version
            docker-compose --version
    - name: Setup Docker-Compose
      run: docker-compose up -d
    - name: Run Tests
      run: docker-compose exec backend sh -c "pytest ."
