name: Django Project Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Docker Compose
      run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
    - name: Setup Docker-Compose
      run: docker-compose up -d
    - name: Run Tests
      run: docker-compose exec backend sh -c "pytest ."
